[workspace]
members = [
  "day1-expense-report",
  "day2-password-policy",
  "day3-toboggan-trajectory",
  "day4-passport-processing",
  "day5-binary-boarding",
  "day6-custom-customs",
  # template insert here

  "lib",
]
exclude = ["template"]
